information_dic = {
    "tomato": "1",
    "carrot": "4",
    "beans": "6",
    "beets": "7",
    "broccoli": "8",
    "cabbage": "10",
    "cauliflower": "11",
    "cucumber": "15",
    "maize": "16",
    "eggplant": "17",
    "onion": "18",
    "garlic": "19",
    "peas": "23",
    "bell pepper": "24",
    "potato": "25",
    "pumpkin": "26",
    "radish": "27",
    "spinach": "29",
    "turnip": "32",
    "watermelon": "33",
    "rosemary": "37",
    "sweet potato": "44"
}

image_dic = {
    "tomato": "https://www.gardeningknowhow.com/wp-content/uploads/2017/06/zone-9-tomatoes-400x267.jpg",
    "carrot": "https://www.rhs.org.uk/getmedia/2245b064-2a40-47dc-9e40-a80944b93dba/carrot_RHS_PUB0027899_940x627.jpg?width=940&height=627&ext=.jpg",
    "beans": "https://www.almanac.com/sites/default/files/styles/amp_metadata_content_image_min_696px_wide/public/image_nodes/green_beans_brytta_gettyimages.jpg?itok=qFcJv2XH",
    "beets": "https://www.almanac.com/sites/default/files/image_nodes/beets_by_darasp_kran_ss_crop.jpg",
    "broccoli": "https://www.almanac.com/sites/default/files/styles/amp_metadata_content_image_min_696px_wide/public/image_nodes/broccoli-plant.jpg?itok=DxKCKhXb",
    "cabbage": "https://gardenerspath.com/wp-content/uploads/2019/09/Heads-of-cabbage-Brassica-oleracea-var.-capitata.jpg",
    "cauliflower": "https://gardenerspath.com/wp-content/uploads/2019/03/How-to-Grow-Cauliflower-Cover.jpg",
    "cucumber": "https://thepracticalplanter.com/wp-content/uploads/2021/03/IS-Cucumber-Plant.jpg",
    "maize": "https://blog.mr-fothergills.co.uk/site/wp-content/uploads/2018/06/Mr-Fothergills-growing-super-sweet-corn-1024x678.jpg",
    "eggplant": "https://www.nature-and-garden.com/wp-content/uploads/sites/4/2018/10/eggplant.jpg",
    "onion": "https://naturebring.com/wp-content/uploads/2019/02/Onion-nb-023.jpg",
    "garlic": "https://gardenerspath.com/wp-content/uploads/2019/12/Bunch-of-Purple-Garlic-Harvested-and-Cleaned.jpg",
    "peas": "https://www.growerexperts.com/wp-content/uploads/2018/09/when-to-sow-peas-1.jpg",
    "bell pepper": "https://www.gardeningknowhow.com/wp-content/uploads/2009/03/iStock-530253685.jpg",
    "potato": "https://hydrobuilder.com/wp/wp-content/uploads/Growing_Potato_Plants.jpg",
    "pumpkin": "https://hgtvhome.sndimg.com/content/dam/images/hgtv/stock/2018/3/22/01/shutterstock_Maria-Uspenskaya_87149521_pumpkin-growing.jpg.rend.hgtvcom.616.440.suffix/1521747206945.jpeg",
    "radish": "https://gardenerspath.com/wp-content/uploads/2017/05/Grow-Winter-Radish-Like-Daikon.jpg",
    "spinach": "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/981/articles/2018/02/growingspinach-1000-0-1519138802.jpg",
    "turnip": "https://ogden_images.s3.amazonaws.com/www.motherearthgardener.com/images/2017/02/19163606/turnips-jpg.jpg",
    "watermelon": "https://www.gardeningknowhow.com/wp-content/uploads/2017/02/watermelon-thinnning.jpg",
    "rosemary": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Rosemary_in_bloom.JPG",
    "sweet potato": "https://www.gardeningknowhow.com/wp-content/uploads/2009/04/sweet-potatoes.jpg",
    "rice": "https://cdn.britannica.com/89/140889-050-EC3F00BF/Ripening-heads-rice-Oryza-sativa.jpg",
    "chickpea": "https://cdn.harvesttotable.com/htt/2009/04/23180911/Chickpeas-bigstock-Fresh-Green-Chickpeas-Field-337227136-scaled.jpg",
    "kidneybeans": "https://plantinstructions.com/wp-content/uploads/2019/01/kidney-bean.jpg",
    "pigeonpeas": "https://www.ugaoo.com/media/wysiwyg/pigeonpea_hwh1.jpg",
    "mungbean": "https://www.feedipedia.org/sites/default/files/images/mung_bean_pods.jpg",
    "mothbeans": "https://img.plantsam.com/wp-content/uploads/2014/01/moth-beans.jpg",
    "blackgram": "https://www.agrifarming.in/wp-content/uploads/2015/04/Black-Gram-Production..jpg",
    "lentil": "https://morningchores.com/wp-content/uploads/2020/05/Growing-Lentils-Varieties-Planting-Guide-Care-Problems-and-Harvest-FB.jpg",
    "pomegranate": "https://www.gardeningknowhow.com/wp-content/uploads/2020/11/pomegranate-hanging-from-a-tree-400x300.jpg",
    "mango": "https://tiimg.tistatic.com/fp/1/006/667/fresh-rataul-mango-plant-473.jpg",
    "banana": "https://bloximages.newyork1.vip.townnews.com/nola.com/content/tncms/assets/v3/editorial/e/69/e69e8bb2-b85c-5894-9bf7-ba9cc9104d04/5d13ccd19b6b2.image.jpg?crop=484%2C484%2C90%2C0&resize=1200%2C1200&order=crop%2Cresize",
    "grapes": "https://www.almanac.com/sites/default/files/image_nodes/green-grapes.jpg",
    "muskmelon": "https://cdn.harvesttotable.com/htt/2009/03/23181230/Melon-muskmelon-2.jpg",
    "apple": "https://5.imimg.com/data5/MS/CC/NT/SELLER-13447959/anna-apple-plant-low-chill-hot-areas--500x500.jpg",
    "orange": "https://thumbs.dreamstime.com/b/orange-tree-9124950.jpg",
    "papaya": "https://5.imimg.com/data5/SV/HB/SE/SELLER-19153449/fresh-papaya-500x500.jpg",
    "coconut": "https://www.greensofkerala.com/wp-content/uploads/2020/09/malaysian-dwarf-coconut-plant.jpg",
    "cotton": "https://5.imimg.com/data5/PH/MO/BY/SELLER-72269125/cotton-plant-500x500.jpg",
    "jute": "https://bangladeshpost.net/webroot/uploads/featureimage/2019-05/5cd400aa43bce.jpg",
    "coffee": "https://morningchores.com/wp-content/uploads/2019/11/Growing-Coffee-Best-Varieties-Planting-Guide-Care-Problems-and-Harvest-FI.jpg",

}

